<?php

return [
    'frontend_url' => env('FRONTEND_URL', 'http://localhost:3000'),

    // Super-admin MFA. Keep true in production. Set false only for local development.
    'require_super_admin_mfa' => filter_var(
        env('SUVAKAMANA_REQUIRE_SUPER_ADMIN_MFA', true),
        FILTER_VALIDATE_BOOLEAN
    ),

    'platform_restaurant_slug' => env('SUVAKAMANA_RESTAURANT_SLUG', 'suvakamana-restaurant'),
    'platform_restaurant_name' => env('SUVAKAMANA_RESTAURANT_NAME', 'Suvakamana Restaurant'),

    'login' => [
        'max_attempts' => (int) env('AUTH_MAX_LOGIN_ATTEMPTS', 5),
        'lock_minutes' => (int) env('AUTH_LOCK_MINUTES', 15),
    ],

    'roles' => [
        'customer',
        'restaurant_owner',
        'restaurant_manager',
        'restaurant_staff',
        'super_admin',
    ],

    'permissions' => [
        'view_customer_profile',
        'manage_customer_profile',
        'submit_restaurant_application',
        'view_own_restaurant_application',
        'edit_own_restaurant_application',
        'withdraw_own_restaurant_application',
        'view_restaurant_dashboard',
        'manage_restaurant_profile',
        'manage_restaurant_staff',
        'manage_menu',
        'manage_offers',
        'view_orders',
        'manage_orders',
        'view_finance',
        'view_settlements',
        'manage_restaurant_settings',
        'view_restaurant_profile',
        'manage_restaurant_media',
        'manage_restaurant_hours',
        'manage_restaurant_service_areas',
        'activate_restaurant',
        'temporarily_close_restaurant',
        'view_menu',
        'manage_menu_categories',
        'manage_menu_items',
        'manage_menu_variants',
        'manage_menu_modifiers',
        'manage_menu_allergens',
        'manage_menu_availability',
        'manage_restaurant_offers',
        'view_super_admin_dashboard',
        'manage_restaurants',
        'manage_applications',
        'view_restaurant_applications',
        'review_restaurant_applications',
        'request_application_changes',
        'approve_restaurant_applications',
        'reject_restaurant_applications',
        'verify_restaurant_documents',
        'manage_commission_agreements',
        'assign_application_reviewers',
        'manage_commissions',
        'manage_settlements',
        'manage_platform_settings',
        'view_audit_logs',
        'manage_support',
        'view_cart',
        'manage_cart',
        'manage_own_addresses',
        'prepare_checkout',
        'place_order',
        'view_own_orders',
        'cancel_own_order',
        'view_restaurant_orders',
        'accept_restaurant_orders',
        'reject_restaurant_orders',
        'prepare_restaurant_orders',
        'complete_restaurant_orders',
        'cancel_restaurant_orders',
        'view_all_platform_orders',
        'view_platform_order_details',
        'manage_order_exceptions',
        'view_own_order_payment',
        'retry_own_payment',
        'view_restaurant_payment_summaries',
        'request_restaurant_refund',
        'view_all_platform_payments',
        'view_platform_payment_details',
        'create_full_refund',
        'create_partial_refund',
        'view_payment_disputes',
        'retry_failed_webhook',
        'manage_payment_accounts',
    ],
];
